{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "sqlpad.fullname" . }}
  labels:
    {{- include "sqlpad.labels" . | nindent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.parentGatewayName }}
  hostnames:
  {{- range .Values.gateway.hosts }}
    - {{ .host | quote }}
  {{- end }}
  rules:
    - matches:
      {{- range .paths }}
      - path:
          value: {{ .path | quote }}
      {{- end }}
      backendRefs:
        - name: {{ include "sqlpad.fullname" . }}
          port: {{ .Values.service.port }}
{{- end -}}
