apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sqlpad.name" . }}-environment
  labels:
    {{- include "sqlpad.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with $environment := mustMergeOverwrite .Values.environmentBase .Values.environmentOverride }}
  {{- range $key, $value := $environment }}
  {{ $key | quote }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.mariadb.enabled }}
  SQLPAD_BACKEND_DB_URI: {{ include "sqlpad.mariadbConnection" . | b64enc | quote}}
  {{- end}}
